// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG64lThfJPhpYM6f3pqcpPiXbO-rwURVw',
    appId: '1:312448496870:web:7c45d48860591d0b9b7727',
    messagingSenderId: '312448496870',
    projectId: 'instagramclone-508f8',
    authDomain: 'instagramclone-508f8.firebaseapp.com',
    storageBucket: 'instagramclone-508f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7UuPsUOjE8vA9Y4XEUB1pYMTOltk_tc',
    appId: '1:312448496870:android:49c039dae547b06b9b7727',
    messagingSenderId: '312448496870',
    projectId: 'instagramclone-508f8',
    storageBucket: 'instagramclone-508f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5MZwyOGK_8ioAaJu1u962P6EVr6ANF2U',
    appId: '1:312448496870:ios:8c5046b0ca7bb35e9b7727',
    messagingSenderId: '312448496870',
    projectId: 'instagramclone-508f8',
    storageBucket: 'instagramclone-508f8.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5MZwyOGK_8ioAaJu1u962P6EVr6ANF2U',
    appId: '1:312448496870:ios:8c5046b0ca7bb35e9b7727',
    messagingSenderId: '312448496870',
    projectId: 'instagramclone-508f8',
    storageBucket: 'instagramclone-508f8.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG64lThfJPhpYM6f3pqcpPiXbO-rwURVw',
    appId: '1:312448496870:web:43c33a56a09ac8a09b7727',
    messagingSenderId: '312448496870',
    projectId: 'instagramclone-508f8',
    authDomain: 'instagramclone-508f8.firebaseapp.com',
    storageBucket: 'instagramclone-508f8.appspot.com',
  );
}
